FROM  kthregistry.azurecr.io/kth-nodejs-16:latest
# FROM node:16-alpine # Use this for local development
WORKDIR /usr/src/app

ENV TZ Europe/Stockholm

COPY ["package.json", "package.json"]
COPY ["package-lock.json", "package-lock.json"]
COPY ["packages", "packages"]
COPY ["apis", "apis"]

RUN chown -R node:node /usr/src/app

USER node

RUN npm ci --omit=dev --workspace=my-studies-apis

WORKDIR /usr/src/app/apis/my-studies-apis
EXPOSE 3000
CMD ["npm", "start"]