FROM  kthregistry.azurecr.io/kth-nodejs-16:latest
WORKDIR /usr/src/app

ENV NODE_PATH /usr/src/app

ENV TZ Europe/Stockholm

COPY ["package.json", "package.json"]
COPY ["package-lock.json", "package-lock.json"]
COPY ["packages", "packages"]
COPY ["apis", "apis"]

RUN chown -R node:node /usr/src/app

USER node

RUN npm pkg delete scripts.prepare && \
  npm ci --unsafe-perm && \
  npm run build && \
  npm prune --production 

EXPOSE 3000
CMD ["cd apis/my-canvas-rooms-api && npm start"]
