# This Dockerfile uses multi-stage builds as recommended in
# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md
#
FROM node:16-bullseye AS frontend
WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .
COPY kpm .
COPY packages .


# See: https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd
RUN npm ci --development --workspace=kpm-frontend
COPY kpm/kpm-frontend .
RUN npm run build --workspace=kpm-frontend

FROM node:16-alpine AS backend
WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .
COPY kpm .
COPY packages .

RUN npm ci --omit=dev --workspace=kpm-backend

FROM node:16-alpine AS production
WORKDIR /usr/src/app
COPY --from=backend /usr/src/app/node_modules .
COPY --from=backend packages .
COPY --from=backend kpm .
COPY --from=frontend /usr/src/app/kpm/kpm-frontend/distProd kpm/kpm-frontend/distProd

EXPOSE 3000

CMD cd kpm/kpm-backend && npm start
