FROM node:16-alpine
WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .
COPY packages .
COPY apis .

RUN node -v
RUN npm ci --omit=dev --workspace=my-canvas-rooms-api

EXPOSE 3000
CMD cd apis/my-canvas-rooms-api && npm start
