FROM  kthregistry.azurecr.io/kth-nodejs-16:latest
# FROM node:16-alpine
WORKDIR /usr/src/app

ENV TZ Europe/Stockholm

COPY ["package.json", "package.json"]
COPY ["package-lock.json", "package-lock.json"]
COPY ["packages", "packages"]
COPY ["apis", "apis"]

RUN npm ci --omit=dev --workspace=my-teaching-api

WORKDIR /usr/src/app/apis/my-teaching-api
EXPOSE 3000
CMD ["npm", "start"]
