FROM  kthregistry.azurecr.io/kth-nodejs-16:latest
# FROM node:16-alpine
WORKDIR /usr/src/app

ENV TZ Europe/Stockholm

COPY ["package.json", "package.json"]
COPY ["package-lock.json", "package-lock.json"]
COPY ["packages", "packages"]
COPY ["apis", "apis"]

RUN chown -R node:node /usr/src/app
USER node

RUN npm ci --omit=dev --workspace=my-canvas-rooms-api

WORKDIR /usr/src/app/apis/my-canvas-rooms-api
EXPOSE 3000
CMD ["npm", "start"]
