# This Dockerfile uses multi-stage builds as recommended in
# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md
#
FROM node:16-bullseye
WORKDIR /usr/src/app

COPY . .

RUN cd kpm-frontend && npm ci --development
RUN cd kpm-backend && npm ci --development

RUN cd kpm-frontend && npm run build
RUN cd kpm-backend && npm ci --development
