version: "3.2"

services:
  unit_tests:
    build: .
    image: $LOCAL_IMAGE_ID
    tty: false
    command: >
      sh -c "(cd kpm-backend && npm ci --development && npm test) && (cd kpm-frontend && npm ci --development && npm test)"
