pr: none
trigger:
  branches:
    include:
      - stratus-migration

variables:
  - group: elarande-general-params
  - group: elarande-spoke1-ref
  - name: dockerfilePath
    value: '$(Pipeline.Workspace)/github/Dockerfile-kpm'
  - name: appName
    value: kpm-ref
  - name: imageName
    value: kpm
  - name: tag
    value: '${BUILD_BUILDNUMBER}_${BUILD_SOURCEVERSION:0:4}'
  - name: parametersFileName
    value: kpm/ref.parameters.json

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: use-specific-dockerfile-names

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/docker/build.yml@cet-iac
    parameters:
      runScan: true
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)

  - template: templates/test/npm-test.yml@cet-iac
    parameters:
      nodeVersion: '16'
      command: 'test --workspace=kpm'
      installCommand: 'ci --omit=dev --workspace=kpm'

  # - template: templates/test/docker-test.yml@cet-iac
  #   parameters:
  #     imageName: $(imageName)
  #     dockerfilePath: $(dockerfilePath)
  #     tag: $(tag)
  #     dockerComposeFilePaths: 
  #       - '$(Pipeline.Workspace)/github/docker-compose-unit-tests.yml'
  
  - template: templates/docker/push.yml@cet-iac
    parameters:
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)
  
  - template: templates/app-service/update-image.yml@cet-iac
    parameters:
      parametersFileName: $(parametersFileName)
      appName: $(appName)
      imageName: $(imageName)
      tag: $(tag)
      isApi: false